from __future__ import annotations

import urllib.parse
import xml.etree.ElementTree as ET
import re

from embodiedai_kb.paper_search.models import AcademicPaper

from .base import PaperSource
from .common import arxiv_pdf_url, extract_doi, open_bytes, parse_date, stable_id


ATOM_NS = {"a": "http://www.w3.org/2005/Atom", "arxiv": "http://arxiv.org/schemas/atom"}
ARXIV_FIELD_PREFIX_RE = re.compile(r"(?<![\w.])(?:all|ti|au|abs|cat|co):")


def _entry_text(entry: ET.Element, path: str) -> str:
    value = entry.find(path, ATOM_NS)
    if value is None or value.text is None:
        return ""
    return " ".join(value.text.split())


def _format_arxiv_query(query: str) -> str:
    """Preserve arXiv-native field queries generated by the query agent."""

    clean = " ".join(str(query or "").split())
    if ARXIV_FIELD_PREFIX_RE.search(clean):
        return clean
    return f"all:{clean}"


class ArxivSearcher(PaperSource):
    source_name = "arxiv"
    base_url = "https://export.arxiv.org/api/query"

    def search(
        self,
        query: str,
        max_results: int = 10,
        sort_by: str = "relevance",
        sort_order: str = "descending",
        **_: object,
    ) -> list[AcademicPaper]:
        params = {
            "search_query": _format_arxiv_query(query),
            "max_results": max(1, min(max_results, 100)),
            "sortBy": sort_by,
            "sortOrder": sort_order,
        }
        payload = open_bytes(f"{self.base_url}?{urllib.parse.urlencode(params)}")
        root = ET.fromstring(payload)
        papers: list[AcademicPaper] = []
        for entry in root.findall("a:entry", ATOM_NS):
            title = _entry_text(entry, "a:title")
            if not title:
                continue
            url = _entry_text(entry, "a:id")
            arxiv_id = url.rstrip("/").split("/")[-1]
            abstract = _entry_text(entry, "a:summary")
            pdf_url = ""
            for link in entry.findall("a:link", ATOM_NS):
                if link.attrib.get("title") == "pdf" or link.attrib.get("type") == "application/pdf":
                    pdf_url = link.attrib.get("href", "")
                    break
            papers.append(
                AcademicPaper(
                    paper_id=stable_id("arxiv", arxiv_id, title),
                    title=title,
                    authors=[
                        name.text.strip()
                        for author in entry.findall("a:author", ATOM_NS)
                        if (name := author.find("a:name", ATOM_NS)) is not None and name.text
                    ],
                    abstract=abstract,
                    doi=_entry_text(entry, "arxiv:doi") or extract_doi(abstract),
                    published_date=parse_date(_entry_text(entry, "a:published")),
                    updated_date=parse_date(_entry_text(entry, "a:updated")),
                    pdf_url=pdf_url or arxiv_pdf_url(arxiv_id),
                    url=url or f"https://arxiv.org/abs/{arxiv_id}",
                    source=self.source_name,
                    categories=[
                        item.attrib["term"]
                        for item in entry.findall("a:category", ATOM_NS)
                        if item.attrib.get("term")
                    ],
                    extra={"arxiv_id": arxiv_id},
                )
            )
        return papers
